version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: medimap-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jwjw78901!
      MYSQL_DATABASE: medimap
      MYSQL_USER: medimap_user
      MYSQL_PASSWORD: medimap_password
    #ports:
    #  - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  app:
    image: jinupark0708/medimap:latest
    container_name: medimap-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: